# Generated by Django 4.2.2 on 2023-06-25 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 25, 5, 36, 28, 791533, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="todo", name="description", field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="todo", name="title", field=models.CharField(max_length=100),
        ),
    ]
